### ISSUE TITLE
Health/Mana Bar gone

### ISSUE THREAD

**Issue by AnAncientMonk** [Excrulon/Tree-of-Savior-Experience-Viewer-Lua-Mod#3]
After installing the addon (wich is super great btw.)
my health and mana bar + my icon [disappear / freeze](http://puu.sh/nYKOs/8116abafb6.png) after pressing the start button.
Can only fix by restarting the game.
Am i doing it wrong?
Great tool anyways! :3
Have a good day

**Comment by Excrulon** [comment]
No idea what causes this or how to reproduce it. It happens for me very rarely, and it usually goes away eventually (maybe changing maps or something).

**Comment by AnAncientMonk** [comment]
thanks for the fast answer :3 
 ive tried reloging, changing map and changing channel.
but only restarting does it somehow..
ill try and reinstall it 
maybe it will fix itself.
if i can do anything to help you fix it just ask.

**Comment by Excrulon** [comment]
Does it happen 100% of the times you use it?

**Comment by AnAncientMonk** [comment]
I only tested it 3 times so for now its 100% (2xfreeze / 1x disappear)
i cant check right now as im at work. but i will test more when im able to play again.

**Comment by Excrulon** [comment]
I think I know what's causing it. Trying to find a fix now.

**Comment by Excrulon** [comment]
Posted a new release that might fix it. Mind giving it a try?

1.4 https://github.com/Excrulon/Tree-of-Savior-Experience-Viewer-Lua-Mod/releases

**Comment by AnAncientMonk** [comment]
I will get back to you, i promise. Work just takes all my time right now. q.q

**Comment by AnAncientMonk** [comment]
Works perfectly fine now
many thanks Excrulon!
Great Addon you made there.

**Comment by Excrulon** [comment]
No problem, glad it worked.
