### ISSUE TITLE
Health/mana 0 bug, steps to reproduce inside

### ISSUE THREAD

**Issue by temikje** [Excrulon/Tree-of-Savior-Experience-Viewer-Lua-Mod#6]
1) open game with viewer
2) select character
3) place spot for viewer, press "start"
4) use statue for teleport in any location (my opinion is dungeon)
5) get 0/0 hp permanently, character selection didn't help, only full exit game

**Comment by Excrulon** [comment]
Please post any information in the original issue so we can keep track of it in one place... thanks. #3
